"""Auditable bot-username and bot-phrase lists.

Signal A — known bot usernames (exact, case-insensitive)
    BOTWATCH_WIKI: r/autowikibot wiki/redditbots, compiled from r/botwatch.
        https://www.reddit.com/r/autowikibot/wiki/redditbots
        Kept names that look like bot accounts (bot/moderator/tip/wiki/
        transcriber, or AutoModerator / known tip bots). Dropped human-looking
        handles that leaked into that wiki (GreasyBacon, rarchives, etc.).
    MODERN_HELPER_BOTS: helper/mod/utility bots common after that wiki
        snapshot. Curated from eliassjogreen/Reddit-Bot-List, r/bottiquette,
        r/botwatch conventions, and Reddit platform docs (AutoModerator).

Signal B — high-precision self-identification phrases (short, auditable)
    Templates bots emit about themselves, not humans talking about bots.
    Probe pass excluded "chatgpt", "as an ai", "good bot", and
    "if you have any questions" (too many human hits).
"""
from __future__ import annotations

import re

BOTWATCH_WIKI = {
    '__bot__',
    '_definition_bot_',
    '_fallacybot_',
    'aabot',
    'adhdbot',
    'albumbot',
    'allinonebot',
    'altcodebot',
    'annoying_yes_bot',
    'antiracism_bot',
    'asmrspambot',
    'asshatbot',
    'astro-bot',
    'atheismmodbot',
    'auto-doge',
    'autoinsult',
    'automoderator',
    'autourbanbot',
    'autowikibot',
    'avr_modbot',
    'bad_ball_ban_bot',
    'badlinguisticsbot',
    'banishedbot',
    'baseball_gif_bot',
    'beecointipbot',
    'beetusbot',
    'belitipbot',
    'bensonthebot',
    'bible_verses_bot',
    'bitcoinpartybot',
    'bitcointip',
    'bitofnewsbot',
    'blackjackbot',
    'blockchainbot',
    'bocketybot',
    'brigade_bot',
    'brmt_bot',
    'bronze-bot',
    'c5bot',
    'cah_black_bot',
    'cakeday-bot',
    'callfloodbot',
    'callibot',
    'calvinbot',
    'canada_goose_tip_bot',
    'captionbot',
    'carterdugsublinkbot',
    'casualmetricbot',
    'changetip',
    'chart_bot',
    'cheesecointipbot',
    'chemistry_bot',
    'christianitybot',
    'chromabot',
    'classybot',
    'coinflipbot',
    'coinyetipper',
    'colorcodebot',
    'comment_copier_bot',
    'compilebot',
    'complimentingbot',
    'conspirobot',
    'cptmodbot',
    'credditbot',
    'creepiersmilebot',
    'creepysmilebot',
    'cruise_bot',
    'cutebot6969',
    'd3posterbot',
    'ddbotindia',
    'define_bot',
    'definitelybot',
    'deltabot',
    'dgctipbot',
    'dictionary__bot',
    'digitipbot',
    'disapprovalbot',
    'dogelotterymodbot',
    'dogetipbot',
    'dogetipstatsbot',
    'dogewordcloudbot',
    'dotacastingbot',
    'drktipbot',
    'dropbox_bot',
    'earthtipbot',
    'edmprobot',
    'elmatadero_bot',
    'emmabot',
    'epic_face_bot',
    'escapistvideobot',
    'exmobot',
    'expired_link_bot',
    'explanationbot',
    'fact_check_bot',
    'faketipbot',
    'fedora_tip_bot',
    'fedoratipautobot',
    'foreigneducationbot',
    'friendlycamelcasebot',
    'friendsafaribot',
    'frown_bot',
    'frytipbot',
    'fsctipbot',
    'gabencointipbot',
    'gabenizer-bot',
    'gabentipbot',
    'gamedealsbot',
    'gatherer_bot',
    'gatsbot',
    'geekwhackbot',
    'gfy_bot',
    'gfycat-bot-sucksdick',
    'giantbombbot',
    'gifster_bot',
    'givesafuckbot',
    'gocougs_bot',
    'golferbot',
    'googleplusbot',
    'gracefulcharitybot',
    'gracefulclaritybot',
    'gregbot',
    'groompbot',
    'grumbler_bot',
    'gunners_gif_bot',
    'gunnersgifsbot',
    'gunnitbot',
    'haiku_robot',
    'havoc_bot',
    'hce_replacement_bot',
    'hearing-aid_bot',
    'hearing_aid_bot',
    'hearingaid_bot',
    'hit_bot',
    'hockey_gif_bot',
    'hockeygt_bot',
    'howisthisbestof_bot',
    'hscard_display_bot',
    'hwsbot',
    'iagreebot',
    'icouldntcarelessbot',
    'imgurhostbot',
    'imgurtranscriber',
    'imirror_bot',
    'insane_photo_bot',
    'isitdownbot',
    'isitupbot',
    'jerkbot-3hunna',
    'jiffybot',
    'jotbot',
    'jumptobot',
    'karmaconspiracy_bot',
    'keysteal_bot',
    'kittehcointipbot',
    'ksportbot',
    'last_cakeday_bot',
    'lazylinkerbot',
    'link_correction_bot',
    'link_rectifier_bot',
    'linkedcommentbot',
    'linkfixerbot1',
    'linkfixerbot2',
    'linkfixerbot3',
    'linkfixerbotsnr',
    'locationbot',
    'loser_detector_bot',
    'magnifier_bot',
    'makes_small_text_bot',
    'malen-shutup-bot',
    'meme_transcriber',
    'memedad-transcriber',
    'meta_bot',
    'metatasticbot',
    'metric_system_bot',
    'metricpleasebot',
    'mma_gif_bot',
    'moderator-bot',
    'montrealbot',
    'multifunctionbot',
    'mumebot',
    'nascarthreadbot',
    'nazeem_bot',
    'nba_gif_bot',
    'new_eden_news_bot',
    'new_small_text_bot',
    'nflvideobot',
    'nhl_gif_bot',
    'nidalee_bot',
    'nosobstorybot2',
    'not_alot_bot',
    'nslbot',
    'okc_rating_bot',
    'pandatipbot',
    'phoenixbot',
    'pjrp_bot',
    'playlisterbot',
    'playstorelinks_bot',
    'ploungemafiavotebot',
    'pokemonflairbot',
    'politebot',
    'politicbot',
    'ponytipbot',
    'porygon-bot',
    'proselytizerbot',
    'punknrollbot',
    'quiche-bot',
    'qznc_bot',
    'raddit-bot',
    'randnumbot',
    'random-complimentbot',
    'randomtriviabot',
    'rangers_bot',
    'readdit_bot',
    'reads_small_text_bot',
    'readsmalltextbot',
    'realtechpostbot',
    'reddcoingoldbot',
    'redditbots',
    'redditreviewbot',
    'reddtipbot',
    'relevant_news_bot',
    'relevantxkcd-bot',
    'request_bot',
    'requirementsbot',
    'rfootballbot',
    'rfreebandzbot',
    'rhiever-bot',
    'rightsbot',
    'riskyclickbot',
    'rnfl_robot',
    'roger_bot',
    'rubycointipbot',
    'rule_bot',
    'rusetipbot',
    'sakuraibot',
    'sakuraibot_test',
    'satoshitipbot',
    'sentimentviewbot',
    'serendipitybot',
    'shadowbanbot',
    'shadowbannedbot',
    'shibebot',
    'shiny-bot',
    'shittyimagebot',
    'slapbot',
    'slickwom-bot',
    'smctipbot',
    'smile_bot',
    'snapshot_bot',
    'soccer_gif_bot',
    'softwareswap_bot',
    'somalia_bot',
    'some_bot',
    'sports_gif_bot',
    'spursgifs_xposterbot',
    'srs_history_bot',
    'stackbot',
    'starboundbot',
    'stats-bot',
    'steam_bot',
    'stenciltemplatebot',
    'streetfightmirrorbot',
    'subtext-bot',
    'suchmodbot',
    'surveyofredditbot',
    'swtor_helper_bot',
    'techobot',
    'tennis_gif_bot',
    'test_bot0x00',
    'text_reader_bot',
    'theswedishbot',
    'tipmoonbot',
    'tipmoonbot1',
    'tipmoonbot2',
    'titsorgtfo_bot',
    'tittietipbot',
    'topredditbot',
    'totes_meta_bot',
    'ttumblrbots',
    'tweetposter',
    'unobtaniumtipbot',
    'urbandicbot',
    'uselessarithmeticbot',
    'uselessconversionbot',
    'valkyribot',
    'versebot',
    'vertcoinbot',
    'vertcointipbot',
    'videolinkbot',
    'videopokerbot',
    'vsaucebot',
    'website_mirror_bot',
    'weeabot',
    'wheres_the_karma_bot',
    'whowouldwinbot',
    'wiki_bot',
    'wiki_firstpara_bot',
    'wikipediacitationbot',
    'wink-bot',
    'wooshbot',
    'wordcloudbot2',
    'writingpromptsbot',
    'wwe_network_bot',
    'x_bot',
    'xkcd_bot',
    'xkcd_number_bot',
    'xkcd_transcriber',
    'xkcdcomic_bot',
    'yourebot',
    'yt_bot',
}

# Post-2016 / still-active helper, mod, and utility bots. Names lowercase.
MODERN_HELPER_BOTS = {
    "automoderator",  # Reddit built-in
    "remindmebot",  # eliassjogreen/Reddit-Bot-List
    "totesmessenger",  # successor of totes_meta_bot
    "wikitextbot",
    "wikipediatextbot",
    "wikipedia_answer_bot",
    "wikimobilelinkbot",
    "linkfixerbot",
    "amputatorbot",
    "savevideobot",
    "vredditshare",
    "vredditdownloader",
    "gifendore",
    "stabbot",
    "deepfrybot",
    "profanitycounter",
    "repostsleuthbot",
    "maximagebot",
    "of_patrol_bot",
    "sneakpeekbot",
    "haikusbot",
    "sokkahaikubot",
    "exclaim_bot",
    "thegratitudebot",
    "alphabet_order_bot",
    "anti-thisbot-ib",
    "bot-sleuth-bot",
    "paid-not-payed-bot",
    "the_timezone_bot",
    "timee_bot",
    "grammar-bot-elite",
    "fatfingerhelperbot",
    "portmanteau-bot",
    "commonmisspellingbot",
    "autotldr",
    "helperbot_",
    "b0trank",
    "goodbot_badbot",
    "mentioned_videos",
    "image_linker_bot",
    "amp-is-watching-you",
    "gifv-bot",
    "converterbot",
    "youtubelinksbot",
    "sub_doesnt_exist_bot",
    "table_it_bot",
    "click_responsibly",
    "spambotswatter",
    "thebenshapirobot",
    "bebodypositive",  # health-resource reply bot; self-IDs as a bot
    "eazeaze",  # crisis-hotline reply bot; self-IDs as a bot
}

KNOWN_BOT_AUTHORS = {n.lower() for n in BOTWATCH_WIKI} | {n.lower() for n in MODERN_HELPER_BOTS}

PHRASE_SPECS = [
    (r"\bi am a bot\b", "I am a bot"),
    (r"\bi['’]m a bot\b", "I'm a bot"),
    (r"this action was performed automatically", "this action was performed automatically"),
    (r"this comment was (left|posted) automatically", "this comment was left/posted automatically"),
    (r"\bbleep[,\s]+bloop\b", "bleep, bloop"),
    (r"please contact the moderators of this subreddit", "please contact the moderators of this subreddit"),
]

PHRASE_REGEXES = [(re.compile(pat, re.IGNORECASE), label) for pat, label in PHRASE_SPECS]


def author_is_known_bot(author: str | None) -> bool:
    if not author:
        return False
    return author.lower() in KNOWN_BOT_AUTHORS


def text_has_bot_phrase(text: str | None) -> tuple[bool, str | None]:
    if not text:
        return False, None
    for rx, label in PHRASE_REGEXES:
        if rx.search(text):
            return True, label
    return False, None
